# SPDX-FileCopyrightText: 2026 ALKONTEK <git@alkontek.com>
# SPDX-License-Identifier: BSD-2-Clause

name=do
title=DigitalOcean Custom Image
class=cloud
requires=cloud
parent=cloud
priority=31
status=alpha
kernel=0
