# SPDX-FileCopyrightText: 2026 ALKONTEK <git@alkontek.com>
# SPDX-License-Identifier: BSD-2-Clause

name=terminal
title=Text console and shell and terminal apps
class=local
requires=
parent=
priority=10
status=alpha
kernel=0
default=1
