# SPDX-FileCopyrightText: 2026 ALKONTEK <git@alkontek.com>
# SPDX-License-Identifier: BSD-2-Clause

name=tui
title=Text console and terminal user interface
class=local
requires=terminal
parent=terminal
priority=11
status=stub
kernel=0
