# SPDX-FileCopyrightText: 2026 ALKONTEK <git@alkontek.com>
# SPDX-License-Identifier: BSD-2-Clause

name=gcp
title=Google Compute Engine
class=cloud
requires=cloud
parent=cloud
priority=33
status=stub
kernel=0
