# SPDX-FileCopyrightText: 2026 ALKONTEK <git@alkontek.com>
# SPDX-License-Identifier: BSD-2-Clause

name=desktop
title=Local graphical workstation
class=local
requires=
parent=
priority=20
status=stub
kernel=0
